Add the missing file operations and add the path manipulation
denoland/denobyexample pull request #17
Opened 2022-01-13 15:50 UTC by TeoDev1611

Hello

I added the delete operation and the path manipulation:

- The delete explain how delete a empty and a non empty directory synchronously and async.
- The path manipulation explain how join, the base name, the file from url, the current directory and format the path 👍🏼 

I hope to help you

2022-01-14 11:45 UTC, lucacasonato reviewed
Thanks for taking the time to contribute. I have not yet reviewed the path-operations example. I'll do that soon.

2022-01-14 11:45 UTC, lucacasonato commented on data/deleting-files.ts
> + * interface for deleting files.
```suggestion
 * Deleting files from disk is a common operation. Deno provides a simple
 * interface for deleting files.
```

2022-01-14 11:45 UTC, lucacasonato commented on data/deleting-files.ts
> +// delete this file.
```suggestion
// Files and empty directories can be deleted with the `Deno.remove` API.
```

2022-01-14 11:45 UTC, lucacasonato commented on data/deleting-files.ts
> + * @title Deleting files
```suggestion
 * @title Deleting files and directories
```

2022-01-14 11:45 UTC, lucacasonato commented on data/deleting-files.ts
> +// directory for fix the last error you need set recursive true
```suggestion
// To delete a directory with its contents, set the `recursive` flag on the
// Deno.remove call.
```

2022-01-14 11:45 UTC, lucacasonato commented on data/deleting-files.ts
> +Deno.removeSync("/path/to/populated_dir/or/file", { recursive: true });
```suggestion
// A synchronous version of the API is also available.
Deno.removeSync("/path/to/empty_dir/or/file");
```

2022-01-14 11:45 UTC, lucacasonato commented on data/deleting-files.ts
> + * @run --allow-write <url>
```suggestion
```

2023-01-13 18:10 UTC, lino-levan requested changes
A lot of good work, but somewhat outdated. Please fix these (or just accept the suggested changes).

2023-01-13 18:10 UTC, lino-levan commented on data/path-operations.ts
> +console.log(`PATH 1: ${p1} PATH 2: ${p2}`); // PATH 1: /home/foo PATH 2: \\home\\foo
```suggestion
// Converting from a file url to a directory can be done simply by the `fromFileUrl`
// method from the appropriate implementation.
const p1 = path.posix.fromFileUrl("file:///home/foo");
const p2 = path.win32.fromFileUrl("file:///home/foo");
console.log(`PATH 1: ${p1} PATH 2: ${p2}`); // PATH 1: /home/foo PATH 2: \\home\\foo

// We can also choose to not specify and automatically use whatever Deno is running on
const p3 = path.fromFileUrl("file:///home/foo");
```

2023-01-13 18:10 UTC, lino-levan commented on data/path-operations.ts
> +// You want get the last part of a file path you can use this
```suggestion
// We can get the last part of a file path using the basename method
```

2023-01-13 18:10 UTC, lino-levan commented on data/path-operations.ts
> +// You want get the directory name from a Path
```suggestion
// We can get the directory of a file path using the dirname method
```

2023-01-13 18:10 UTC, lino-levan commented on data/path-operations.ts
> +// You want get the extension from a path
```suggestion
// We can get the extension of a file path using the extname method
```

2023-01-13 18:10 UTC, lino-levan commented on data/path-operations.ts
> +// You want format a path generating from a object
```suggestion
// We can format a path using a FormatInputPathObject
```

2023-01-13 18:10 UTC, lino-levan commented on data/path-operations.ts
> +// You want join files with the os separator
```suggestion
// When we want to make our code cross-platform, we can use the join method.
// This joins any number of string by the OS-specific file seperator
```
We should probably move this up the file as it is probably the most important utility.

2023-01-13 18:10 UTC, lino-levan commented on data/path-operations.ts
> +// You want get the current directory
```suggestion
// We can get the current working directory using the built-in cwd method
```

2023-01-15 18:04 UTC, lino-levan commented
@TeoDev1611 are you willing to move this forward?

2023-01-19 23:57 UTC, lino-levan commented
@TeoDev1611 glad to see you moving this forward. Besides my two remaining comments, this LGTM!

Pinging @crowlKats to please take a look!

2023-01-20 00:19 UTC, TeoDev1611 commented
> @TeoDev1611 glad to see you moving this forward. Besides my two remaining comments, this LGTM!
> 
> Pinging @crowlKats to please take a look!

Thanks for the suggestions, I incorporated all the changes!

2023-01-20 00:29 UTC, lino-levan commented
Perfect! LGTM.

2023-01-20 13:11 UTC, crowlKats commented
could you please run deno fmt?

2023-01-21 17:40 UTC, lino-levan commented on data/path-operations.ts
> +// You want get the extension from a path
```suggestion
// We can get the extension of a file path using the extname method
```

2023-03-10 20:42 UTC, lino-levan commented
@hashrock I believe this should be closed now that #62 got merged

2023-03-10 21:07 UTC, hashrock commented
Yeah! thank you for your contribution @TeoDev1611 !

2023-03-10 21:07 UTC, closed without merging